Remove dual centres for rockford
FormicAcidGD/ptfst-db pull request #6
Opened 2024-08-18 16:14 UTC by awdev1

woopsies i look like i put 2 rockford centres

2025-02-08 03:04 UTC, awdev1 commented
uh

2025-02-25 12:55 UTC, aidenbok203 approved these changes
LGTM

2025-03-22 15:22 UTC, awdev1 commented
Follow up?

2025-04-10 16:16 UTC, awdev1 commented
Follow up?

2025-04-14 17:24 UTC, FormicAcidGD commented
> Follow up?

Being worked on

2025-04-14 18:13 UTC, awdev1 commented
bro its been almost a year

2025-06-21 10:26 UTC, awdev1 commented
bruh

2025-06-21 22:18 UTC, aidenbok203 requested changes
it should be rockford centre

2025-06-23 08:03 UTC, awdev1 commented
It's already set correctly?

2025-06-23 10:59 UTC, aidenbok203 approved these changes

2025-11-08 01:15 UTC, awdev1 commented
hello?

2025-11-14 20:33 UTC, closed without merging